- name: Information
  hosts:
    - all
  gather_facts: false
  become: false
  tasks:
    - name: Information
      changed_when: false
      ansible.builtin.shell:
        cmd: |
          exec 2>&1
          set -x
          cat /System/Library/CoreServices/SystemVersion.plist
          system_profiler SPSoftwareDataType
          sw_vers
          uname -a
          hostname
          ifconfig
