- name: Set the computer time server
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'set-computer-time-server.sh') }}"
  environment:
    ARG_COMPUTER_TIME_SERVER: "{{ system_time_server }}"
  register: system_result
  changed_when: "'ANSIBLE CHANGED NO' not in system_result.stdout_lines"

- name: Disable the computer sleep
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: "{{ lookup('file', 'set-computer-sleep.sh') }}"
  environment:
    ARG_COMPUTER_SLEEP: Never
  register: system_result
  changed_when: "'ANSIBLE CHANGED NO' not in system_result.stdout_lines"

- name: Disable the login screen saver
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.screensaver
    key: loginWindowIdleTime
    type: integer
    value: 0

- name: Disable the desktop screen saver
  community.general.osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: idleTime
    type: integer
    value: 0
