# see https://brew.sh
# see https://docs.brew.sh/Analytics
# see https://docs.brew.sh/Installation
# see https://github.com/Homebrew/install/#install-homebrew-on-macos-or-linux

- name: Install homebrew
  block:
    - name: Check homebrew installed
      ansible.builtin.stat:
        path: "{{ (ansible_architecture == 'x86_64') | ternary('/usr/local/bin/brew', '/opt/homebrew/bin/brew') }}"
      register: homebrew_check
    - name: Install homebrew
      ansible.builtin.shell:
        cmd: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_check.stat.exists
      changed_when: not homebrew_check.stat.exists

- name: Disable brew analytics
  ansible.builtin.command:
    cmd: /bin/bash /dev/stdin
    stdin: "{{ lookup('file', 'disable-brew-analytics.sh') }}"
  register: homebrew_result
  changed_when: "'ANSIBLE CHANGED NO' not in homebrew_result.stdout_lines"

- name: Upgrade homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Upgrade homebrew packages
  community.general.homebrew:
    upgrade_all: true

- name: Upgrade homebrew casks
  # NB this always reports changes.
  #    see https://github.com/ansible-collections/community.general/issues/1647
  community.general.homebrew_cask:
    upgrade_all: true
    greedy: true
