# see https://formulae.brew.sh/formula/htop
- name: Install htop
  community.general.homebrew:
    name: htop

# see https://formulae.brew.sh/formula/sevenzip
- name: Install sevenzip
  community.general.homebrew:
    name: sevenzip

# see https://formulae.brew.sh/formula/jq
- name: Install jq
  community.general.homebrew:
    name: jq
